version: "3.9"
services:
  webhooks:
    image: "stelzo/ankama-discord-hooks:latest"
    ports:
      - "3000:3000"
    environment:
      - API_PORT=3000
      - TWITTER_TOKEN
      - RSS_POLLING_RATE
      - POSTGRES_URL=postgres://postgres:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
      - TWITTER_POLLING_RATE
      - ALMANAX_POLLING_RATE
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./migrations/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/db.sql
    #    - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"